% Created by: Anthony Le
% Last udpated: 03.18.2018

% KIN 523: Homework 8 - Work, Power, Energy, and Force Estimation
% Due: 03.16.18
%%
close all;
clear;

load('HW8_Data.mat');

f_s = 120;
delta_t = 1 / f_s;
time = frame .* delta_t;

% Problem 5
r_AchT = 4.5 / 100; % Achilles Tendon moment arm in m
r_TibA = 4.3 / 100; % Tibialis Anterior moment arm in m

F_AchT = RJM ./ r_AchT;
F_TibA = RJM ./ r_TibA;

figure(1);
plot(time, F_AchT);
xlim([0 2.4]);
xlabel('Time (s)');
ylabel('Force (N)');
title('Force generated by Triceps surae over Time');

figure(2);
plot(time, F_TibA);
xlim([0 2.4]);
xlabel('Time (s)');
ylabel('Force (N)');
title('Force Generated by Tibialis anterior over Time');

% Problem 6
max_stress = 30; % in N/cm^2
Sol_PCSA = 69; % in cm^2
MG_PCSA = 26; % in cm^2
LG_PCSA = 10; % in cm^2

max_F_idx = find(F_AchT == max(F_AchT)); % indx = 113, frame = 112

% part a
a = RJM(max_F_idx) / (max_stress * ((r_AchT * Sol_PCSA) + (r_AchT * MG_PCSA) + (r_AchT * LG_PCSA)));

% part b
F_Sol = a * max_stress * Sol_PCSA; % in N
F_MG = a * max_stress * MG_PCSA; % in N
F_LG = a * max_stress * LG_PCSA; % in N

max_isoF = max_stress * (Sol_PCSA + MG_PCSA + LG_PCSA);

percent_Fm = (F_AchT(max_F_idx) / max_isoF) * 100; % or a * 100

% Problem 7
F_contactC = RJF_C - (F_Sol + F_MG + F_LG);
F_contactS = RJF_S - (F_Sol + F_MG + F_LG);

